### ISSUE TITLE
请问运行时发生空指针异常是什么原因？

### ISSUE THREAD

**Issue by Fireworm007** [wangqifan/toutiao#1]
Exception in thread "Thread-14" java.lang.NullPointerException
	at com.wangqifan.toutiao.async.EventConsumer$1.run(EventConsumer.java:53)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wangqifan** [comment]
看看  com.wangqifan.toutiao.util的第153行  应该是这里发生了异常，返回了NULL  没有判空 你可以把这个bug修改一下 感兴趣的话可以帮忙维护这个项目 谢谢

**Comment by wangqifan** [comment]
你装了Redis吗

**Comment by Fireworm007** [comment]
新手刚入门，Redis还没有接触过。还是先学好项目中用到的技术，再来参考这个项目。

**Comment by wangqifan** [comment]
加油  其实牛客网项目课不错 你可以看下
